language: php
php:
  - 7.4
services:
  - mysql
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e "create database IF NOT EXISTS inventory;" -uroot;
  - php artisan key:generate
  - php artisan migrate:fresh
script:
  - vendor/bin/phpunit --coverage-text